/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#00327d",
        "primary-container": "#0047ab",
        "on-primary": "#ffffff",
        "on-primary-container": "#a5bdff",
        "primary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b1c5ff",
        "on-primary-fixed": "#001946",
        "on-primary-fixed-variant": "#00419e",
        "secondary": "#515f78",
        "secondary-container": "#d2e0fe",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#55637d",
        "secondary-fixed": "#d6e3ff",
        "secondary-fixed-dim": "#b9c7e4",
        "on-secondary-fixed": "#0d1c32",
        "on-secondary-fixed-variant": "#39475f",
        "tertiary": "#2f383b",
        "tertiary-container": "#464f52",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#b7c0c4",
        "tertiary-fixed": "#dbe4e8",
        "tertiary-fixed-dim": "#bfc8cc",
        "on-tertiary-fixed": "#141d20",
        "on-tertiary-fixed-variant": "#3f484b",
        "background": "#f9f9f9",
        "on-background": "#1b1b1b",
        "surface": "#f9f9f9",
        "on-surface": "#1b1b1b",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-container-low": "#f3f3f3",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e2e2e2",
        "on-surface-variant": "#434653",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-tint": "#2559bd",
        "outline": "#737784",
        "outline-variant": "#c3c6d5",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f1f1f1",
        "inverse-primary": "#b1c5ff"
      },
      spacing: {
        'margin': '32px',
        'gutter': '24px',
        'xl': '64px',
        'lg': '40px',
        'md': '24px',
        'sm': '16px',
        'xs': '8px',
        'base': '4px',
      },
      fontFamily: {
        'display': ['Lexend', 'sans-serif'],
        'headline-lg': ['Lexend', 'sans-serif'],
        'headline-md': ['Lexend', 'sans-serif'],
        'body-lg': ['Archivo Narrow', 'sans-serif'],
        'body-md': ['Archivo Narrow', 'sans-serif'],
        'label-bold': ['Archivo Narrow', 'sans-serif'],
      },
      boxShadow: {
        'neo-sm': '2px 2px 0px 0px rgba(0,0,0,1)',
        'neo': '4px 4px 0px 0px rgba(0,0,0,1)',
        'neo-md': '6px 6px 0px 0px rgba(0,0,0,1)',
        'neo-lg': '8px 8px 0px 0px rgba(0,0,0,1)',
        'neo-xl': '12px 12px 0px 0px rgba(0,0,0,1)',
      }
    },
  },
  plugins: [],
}
